# Generated by Django 6.0.1 on 2026-01-29 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='energy_meter_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='raw_material_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilograms'), ('tons', 'Tons'), ('liters', 'Liters'), ('pieces', 'Pieces')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='asset_management_api.client'),
        ),
    ]
