# Generated by Django 6.0.1 on 2026-01-30 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0002_asset_energy_meter_id_asset_raw_material_unit_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
