# Generated by Django 6.0.1 on 2026-01-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0003_alter_signupuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
