# Generated by Django 6.0.1 on 2026-01-30 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0004_alter_signupuser_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signupuser',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
