# Generated by Django 6.0.1 on 2026-01-31 07:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0005_alter_signupuser_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='processed_id',
            new_name='client_code',
        ),
        migrations.RemoveField(
            model_name='asset',
            name='processed_id',
        ),
        migrations.AlterField(
            model_name='asset',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='client',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='process',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='assets',
            field=models.ManyToManyField(blank=True, related_name='production_lines', to='asset_management_api.asset'),
        ),
        migrations.AlterField(
            model_name='productionline',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
