# Generated by Django 6.0.1 on 2026-02-03 07:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0006_rename_processed_id_client_client_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='client_code',
        ),
        migrations.AddField(
            model_name='asset',
            name='asset_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='production_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='client',
            name='client_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='process',
            name='process_id',
            field=models.CharField(blank=True, editable=False, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='asset_management_api.client'),
        ),
        migrations.AlterField(
            model_name='asset',
            name='output_unit',
            field=models.CharField(blank=True, choices=[('kg', 'Kilograms'), ('units', 'Units'), ('liters', 'Liters'), ('meters', 'Meters')], max_length=20, null=True),
        ),
    ]
