# Generated by Django 6.0.1 on 2026-02-04 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0010_remove_asset_production_id_alter_asset_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(max_length=255, null=True, unique=True),
        ),
    ]
