# Generated by Django 6.0.1 on 2026-02-04 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0011_alter_client_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='geo_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='asset',
            name='name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
