# Generated by Django 6.0.1 on 2026-02-05 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0012_client_geo_location_client_ip_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
