# Generated by Django 6.0.1 on 2026-02-05 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0013_alter_client_ip_address'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='geo_location',
        ),
    ]
