# Generated by Django 6.0.1 on 2026-02-05 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0014_remove_client_geo_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='ip_address',
            field=models.GenericIPAddressField(null=True),
        ),
    ]
