# Generated by Django 6.0.1 on 2026-02-05 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0015_asset_ip_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='geo_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='geo_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
