# Generated by Django 6.0.1 on 2026-02-05 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0016_asset_geo_location_client_geo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='geo_location',
        ),
        migrations.RemoveField(
            model_name='client',
            name='geo_location',
        ),
        migrations.AddField(
            model_name='asset',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asset',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='city',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='country',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='region',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
