# Generated by Django 6.0.1 on 2026-02-06 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0017_remove_asset_geo_location_remove_client_geo_location_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='geo_location',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='client',
            name='geo_location',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
