# Generated by Django 6.0.1 on 2026-02-09 07:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset_management_api', '0018_asset_geo_location_client_geo_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='asset',
            name='geo_location',
        ),
        migrations.AlterField(
            model_name='productionline',
            name='client',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='production_lines', to='asset_management_api.client'),
        ),
    ]
